#/bin/bash



root -l -b -q 'mult.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'xn.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'yn.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'zn.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'twoD.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'dLn.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'tof.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'

root -l -b -q 'thetan.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'phin.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'pn.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'

root -l -b -q 'pT.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'thetanq.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'phinq.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'as.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'xp.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'wp.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'virt.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'




# Electron quantities:

root -l -b -q 'pe.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'thetae.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'phie.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'

root -l -b -q 'q.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'thetaq.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'phiq.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'

root -l -b -q 'vtx.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'vty.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'vtz.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'

root -l -b -q 'xB.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'Q2.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'W2.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'
root -l -b -q 'omega.C("/Volumes/BAND-Data/v3.1/10.2/final/data_tagged_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/mixed_tagged_10electrons_5MeV_250mevc_fiducial_thetaCut_allBars.root","/Volumes/BAND-Data/v3.1/10.2/final/sim_mctagged_5MeV_250mevc_fiducial_thetaCut_allBars.root")'

gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=tagged_compare_thetaCut_10pt2_250mevc_cuton250320_Edep10_nofirstbar.pdf full_*
